version: "3.7"
services:
  app:
    build:
      args:
          user: www
          uid: 1000
      context: ./
      dockerfile: Dockerfile
    image: laravel-image-kodefi
    container_name: news
    restart: unless-stopped
    ports:
        - "8000:80"
    working_dir: /var/www/
    environment:
        APP_URL: http://localhost
        DB_CONNECTION: mysql
        DB_HOST: db
        DB_PORT: 3306
        DB_DATABASE: react_laravel_news
        DB_USERNAME: root
        DB_PASSWORD: root
    volumes:
      - ../:/var/www
    networks:
      - app-network

  db:
    image: mysql:5.7
    container_name: news_db
    restart: unless-stopped
    ports:
      - "3306:3306"
    environment:
      - "MYSQL_ROOT_PASSWORD=root"
      - "MYSQL_DATABASE=react_laravel_news"
    volumes:
      - ./mysql/my.cnf:/etc/mysql/my.cnf
      - ./mysql/docker-entrypoint-initdb.d/:/docker-entrypoint-initdb.d/
    networks:
      - app-network

  phpmyadmin:
    image: phpmyadmin
    ports:
      - "8082:80"
    environment:
      - "PMA_HOST=db"
      - "UPLOAD_LIMIT:30M"
    networks:
      - app-network
networks:
  app-network:
    driver: bridge
